spring:
  h2:
    console:
      enabled: false

allowed-origins: http://localhost:3000
default-password: password

---

spring:
  jpa:
    generate-ddl: true
  config:
    activate:
      on-profile: prod

allowed-origins: "https://www.firstlegoleague.win,https://*.vercel.app"

logging:
  level:
    org:
      hibernate: error
      springframework.core: error
      springframework.web: error
    root: error
